
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className="min-h-full flex flex-col pt-[88px] lg:pt-[96px]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}


